[build]
# Directorio base
base = "/"

# Comando de construcci칩n
command = """
  # Crear un directorio para Flutter dentro del repositorio
  mkdir -p $HOME/flutter

  # Clonar el repositorio de Flutter en el directorio creado
  git clone https://github.com/flutter/flutter.git $HOME/flutter

  # Agregar Flutter al PATH
  export PATH="$HOME/flutter/bin:$PATH"

  # Verificar la instalaci칩n de Flutter
  flutter doctor

  # Instalar las dependencias del proyecto
  flutter pub get

  # Construir la aplicaci칩n para la web
  flutter build web
"""

# Directorio de salida donde Netlify buscar치 los archivos construidos
publish = "build/web"